"""initial schema"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260325_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("clusters", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("name", sa.String(length=255), nullable=False), sa.Column("slug", sa.String(length=255), nullable=False), sa.Column("description", sa.Text(), nullable=True), sa.Column("parent_cluster_id", sa.Uuid(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("slug"))
    op.create_table("keywords", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("cluster_id", sa.Uuid(), nullable=False), sa.Column("keyword", sa.String(length=255), nullable=False), sa.Column("search_intent", sa.String(length=100), nullable=False), sa.Column("priority", sa.Integer(), nullable=False), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("notes", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("content_topics", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("cluster_id", sa.Uuid(), nullable=False), sa.Column("keyword_id", sa.Uuid(), nullable=True), sa.Column("working_title", sa.String(length=255), nullable=False), sa.Column("target_query", sa.String(length=255), nullable=False), sa.Column("audience", sa.String(length=255), nullable=False), sa.Column("content_type", sa.String(length=100), nullable=False), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("cannibalization_hash", sa.String(length=255), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"]), sa.ForeignKeyConstraint(["keyword_id"], ["keywords.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("sources", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("topic_id", sa.Uuid(), nullable=False), sa.Column("source_type", sa.String(length=50), nullable=False), sa.Column("url", sa.String(length=2048), nullable=False), sa.Column("title", sa.String(length=500), nullable=False), sa.Column("author", sa.String(length=255), nullable=True), sa.Column("published_at", sa.DateTime(timezone=True), nullable=True), sa.Column("transcript_text", sa.Text(), nullable=True), sa.Column("raw_content", sa.Text(), nullable=True), sa.Column("cleaned_content", sa.Text(), nullable=True), sa.Column("reliability_score", sa.Float(), nullable=True), sa.Column("ingestion_status", sa.String(length=50), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["topic_id"], ["content_topics.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("research_notes", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("topic_id", sa.Uuid(), nullable=False), sa.Column("source_id", sa.Uuid(), nullable=True), sa.Column("fact_type", sa.String(length=100), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("confidence_score", sa.Float(), nullable=False), sa.Column("citation_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["source_id"], ["sources.id"]), sa.ForeignKeyConstraint(["topic_id"], ["content_topics.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("briefs", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("topic_id", sa.Uuid(), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("brief_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("prompt_snapshot", sa.Text(), nullable=False), sa.Column("model_name", sa.String(length=255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["topic_id"], ["content_topics.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("articles", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("topic_id", sa.Uuid(), nullable=False), sa.Column("brief_id", sa.Uuid(), nullable=False), sa.Column("current_version_id", sa.Uuid(), nullable=True), sa.Column("title", sa.String(length=500), nullable=False), sa.Column("slug", sa.String(length=255), nullable=False), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("quality_score", sa.Float(), nullable=True), sa.Column("risk_score", sa.Float(), nullable=True), sa.Column("cms_post_id", sa.String(length=255), nullable=True), sa.Column("published_url", sa.String(length=2048), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["brief_id"], ["briefs.id"]), sa.ForeignKeyConstraint(["topic_id"], ["content_topics.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("article_versions", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("article_id", sa.Uuid(), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("content_markdown", sa.Text(), nullable=False), sa.Column("content_html", sa.Text(), nullable=False), sa.Column("excerpt", sa.Text(), nullable=True), sa.Column("meta_title", sa.String(length=255), nullable=False), sa.Column("meta_description", sa.String(length=500), nullable=False), sa.Column("faq_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("word_count", sa.Integer(), nullable=False), sa.Column("created_by", sa.String(length=50), nullable=False), sa.Column("generation_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["article_id"], ["articles.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("images", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("article_id", sa.Uuid(), nullable=False), sa.Column("prompt", sa.Text(), nullable=False), sa.Column("alt_text", sa.String(length=500), nullable=False), sa.Column("storage_url", sa.String(length=2048), nullable=True), sa.Column("local_path", sa.String(length=2048), nullable=True), sa.Column("width", sa.Integer(), nullable=True), sa.Column("height", sa.Integer(), nullable=True), sa.Column("is_featured", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["article_id"], ["articles.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("internal_links", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("article_id", sa.Uuid(), nullable=False), sa.Column("target_article_id", sa.Uuid(), nullable=False), sa.Column("anchor_text", sa.String(length=255), nullable=False), sa.Column("placement_context", sa.String(length=255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["article_id"], ["articles.id"]), sa.ForeignKeyConstraint(["target_article_id"], ["articles.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("quality_reports", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("article_version_id", sa.Uuid(), nullable=False), sa.Column("report_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("quality_score", sa.Float(), nullable=False), sa.Column("risk_score", sa.Float(), nullable=False), sa.Column("blocking_issues_count", sa.Integer(), nullable=False), sa.Column("warning_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["article_version_id"], ["article_versions.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("editorial_reviews", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("article_id", sa.Uuid(), nullable=False), sa.Column("article_version_id", sa.Uuid(), nullable=False), sa.Column("reviewer_name", sa.String(length=255), nullable=False), sa.Column("decision", sa.String(length=50), nullable=False), sa.Column("notes", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["article_id"], ["articles.id"]), sa.ForeignKeyConstraint(["article_version_id"], ["article_versions.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("publishing_jobs", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("article_id", sa.Uuid(), nullable=False), sa.Column("target_system", sa.String(length=50), nullable=False), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("retry_count", sa.Integer(), nullable=False), sa.Column("last_error", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["article_id"], ["articles.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("task_runs", sa.Column("id", sa.Uuid(), nullable=False), sa.Column("task_type", sa.String(length=100), nullable=False), sa.Column("entity_type", sa.String(length=100), nullable=False), sa.Column("entity_id", sa.Uuid(), nullable=False), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("input_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("output_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True), sa.Column("error_message", sa.Text(), nullable=True), sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    for table_name in ["task_runs", "publishing_jobs", "editorial_reviews", "quality_reports", "internal_links", "images", "article_versions", "articles", "briefs", "research_notes", "sources", "content_topics", "keywords", "clusters"]:
        op.drop_table(table_name)
